# Generated by Django 4.2.7 on 2023-12-06 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petRecognizer', '0002_petbreed'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200)),
                ('headlineUrl', models.URLField()),
            ],
        ),
    ]
