# Generated by Django 4.2.7 on 2023-12-06 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petRecognizer', '0003_petnews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PetNews',
        ),
    ]
